/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\assets\keyboard.gltf --transform --types -o .\src\components\KeyboardModel.tsx -k -K -j 
Files: .\public\assets\keyboard.gltf [133.01KB] > keyboard-transformed.glb [98.71KB] (26%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useEffect } from 'react'
import { KeyboardController, ModelProps } from './KeyboardConrtoller'

// Hot fix unkonwn type
interface CustomMesh extends THREE.Mesh {
  instanceMatrix?: THREE.InstancedBufferAttribute
}

type GLTFResult = GLTF & {
  nodes: {
    plate: THREE.Mesh
    Cube076: THREE.Mesh
    Cube076_1: THREE.Mesh
    Cube077: THREE.Mesh
    Cube077_1: THREE.Mesh
    Cube078: THREE.Mesh
    Cube078_1: THREE.Mesh
    Cube079: THREE.Mesh
    Cube079_1: THREE.Mesh
    Escape: THREE.Mesh
    KeyA: THREE.Mesh
    KeyZ: THREE.Mesh
    KeyQ: THREE.Mesh
    Tab: THREE.Mesh
    Backslash: THREE.Mesh
    Cube081: THREE.Mesh
    Cube092: THREE.Mesh
    CapsLock: THREE.Mesh
    Cube082: THREE.Mesh
    ShiftLeft: THREE.Mesh
    Cube083: THREE.Mesh
    Cube007: THREE.Mesh
    Cube084: THREE.Mesh
    ControlLeft: THREE.Mesh
    Cube085: THREE.Mesh
    Cube014: THREE.Mesh
    Cube091: THREE.Mesh
    Backspace: THREE.Mesh
    Cube017: THREE.Mesh
    Enter: THREE.Mesh
    Cube018: THREE.Mesh
    Cube094: THREE.Mesh
    Digit1: THREE.Mesh
    KeyS: THREE.Mesh
    KeyX: THREE.Mesh
    KeyW: THREE.Mesh
    Digit2: THREE.Mesh
    KeyD: THREE.Mesh
    KeyC: THREE.Mesh
    KeyE: THREE.Mesh
    Digit3: THREE.Mesh
    KeyF: THREE.Mesh
    KeyV: THREE.Mesh
    KeyR: THREE.Mesh
    Digit4: THREE.Mesh
    KeyG: THREE.Mesh
    KeyB: THREE.Mesh
    KeyT: THREE.Mesh
    Digit7: THREE.Mesh
    KeyK: THREE.Mesh
    Comma: THREE.Mesh
    KeyI: THREE.Mesh
    Digit8: THREE.Mesh
    KeyL: THREE.Mesh
    Period: THREE.Mesh
    KeyO: THREE.Mesh
    Digit9: THREE.Mesh
    Semicolon: THREE.Mesh
    Slash: THREE.Mesh
    KeyP: THREE.Mesh
    Digit0: THREE.Mesh
    Quote: THREE.Mesh
    BracketLeft: THREE.Mesh
    Minus: THREE.Mesh
    Equal: THREE.Mesh
    BracketRight: THREE.Mesh
    Cube070: CustomMesh
    Cube070_1: CustomMesh
    Cube013: CustomMesh
    Cube032: CustomMesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/public/assets/keyboard-transformed.glb') as GLTFResult

  const meshRefs = props.controller.keyboardRef

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh ref={meshRefs.current.plate} name="plate" geometry={nodes.plate.geometry} material={materials.PaletteMaterial001} position={[0.001, -0.013, -0.001]} />
        <group name="Cube026" position={[-0.097, -0.005, -0.03]} rotation={[-3.089, 0, 0]} scale={0.5}>
          <mesh ref={meshRefs.current.Cube076} name="Cube076" geometry={nodes.Cube076.geometry} material={materials.PaletteMaterial001} />
          <mesh ref={meshRefs.current.Cube076_1} name="Cube076_1" geometry={nodes.Cube076_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Cube019" position={[-0.077, -0.006, -0.016]} rotation={[-3.089, 0, 0]} scale={0.5}>
          <mesh ref={meshRefs.current.Cube077} name="Cube077" geometry={nodes.Cube077.geometry} material={materials.PaletteMaterial001} />
          <mesh ref={meshRefs.current.Cube077_1} name="Cube077_1" geometry={nodes.Cube077_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Cube027" position={[-0.072, -0.007, -0.001]} rotation={[-3.089, 0, 0]} scale={0.5}>
          <mesh ref={meshRefs.current.Cube078} name="Cube078" geometry={nodes.Cube078.geometry} material={materials.PaletteMaterial001} />
          <mesh ref={meshRefs.current.Cube078_1} name="Cube078_1" geometry={nodes.Cube078_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Cube028" position={[-0.067, -0.007, 0.014]} rotation={[-3.089, 0, 0]} scale={0.5}>
          <mesh ref={meshRefs.current.Cube079} name="Cube079" geometry={nodes.Cube079.geometry} material={materials.PaletteMaterial001} />
          <mesh ref={meshRefs.current.Cube079_1} name="Cube079_1" geometry={nodes.Cube079_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh ref={meshRefs.current.Escape} name="Escape" geometry={nodes.Escape.geometry} material={materials.PaletteMaterial001} position={[-0.097, 0.002, -0.029]} rotation={[0.052, -0.017, 0.001]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyA} name="KeyA" geometry={nodes.KeyA.geometry} material={materials.PaletteMaterial001} position={[-0.072, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyZ} name="KeyZ" geometry={nodes.KeyZ.geometry} material={materials.PaletteMaterial001} position={[-0.067, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyQ} name="KeyQ" geometry={nodes.KeyQ.geometry} material={materials.PaletteMaterial001} position={[-0.077, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Tab} name="Tab" geometry={nodes.Tab.geometry} material={materials.PaletteMaterial001} position={[-0.095, 0.002, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Backslash} name="Backslash" geometry={nodes.Backslash.geometry} material={materials.PaletteMaterial001} position={[0.097, 0.002, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube081} name="Cube081" geometry={nodes.Cube081.geometry} material={materials.PaletteMaterial001} position={[-0.095, 0.002, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube092} name="Cube092" geometry={nodes.Cube092.geometry} material={materials.PaletteMaterial001} position={[0.097, 0.002, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.CapsLock} name="CapsLock" geometry={nodes.CapsLock.geometry} material={materials.PaletteMaterial001} position={[-0.092, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube082} name="Cube082" geometry={nodes.Cube082.geometry} material={materials.PaletteMaterial001} position={[-0.092, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.ShiftLeft} name="ShiftLeft" geometry={nodes.ShiftLeft.geometry} material={materials.PaletteMaterial001} position={[-0.09, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube083} name="Cube083" geometry={nodes.Cube083.geometry} material={materials.PaletteMaterial001} position={[-0.09, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube007} name="Cube007" geometry={nodes.Cube007.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube084} name="Cube084" geometry={nodes.Cube084.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.ControlLeft} name="ControlLeft" geometry={nodes.ControlLeft.geometry} material={materials.PaletteMaterial001} position={[-0.096, -0.001, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube085} name="Cube085" geometry={nodes.Cube085.geometry} material={materials.PaletteMaterial001} position={[-0.096, -0.001, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube014} name="Cube014" geometry={nodes.Cube014.geometry} material={materials.PaletteMaterial001} position={[0.096, -0.001, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube091} name="Cube091" geometry={nodes.Cube091.geometry} material={materials.PaletteMaterial001} position={[0.096, -0.001, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Backspace} name="Backspace" geometry={nodes.Backspace.geometry} material={materials.PaletteMaterial001} position={[0.094, 0.003, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube017} name="Cube017" geometry={nodes.Cube017.geometry} material={materials.PaletteMaterial001} position={[0.093, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Enter} name="Enter" geometry={nodes.Enter.geometry} material={materials.PaletteMaterial001} position={[0.093, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube018} name="Cube018" geometry={nodes.Cube018.geometry} material={materials.PaletteMaterial001} position={[0.088, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Cube094} name="Cube094" geometry={nodes.Cube094.geometry} material={materials.PaletteMaterial001} position={[0.088, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Digit1} name="Digit1" geometry={nodes.Digit1.geometry} material={materials.PaletteMaterial001} position={[-0.083, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyS} name="KeyS" geometry={nodes.KeyS.geometry} material={materials.PaletteMaterial001} position={[-0.058, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyX} name="KeyX" geometry={nodes.KeyX.geometry} material={materials.PaletteMaterial001} position={[-0.053, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyW} name="KeyW" geometry={nodes.KeyW.geometry} material={materials.PaletteMaterial001} position={[-0.063, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Digit2} name="Digit2" geometry={nodes.Digit2.geometry} material={materials.PaletteMaterial001} position={[-0.069, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyD} name="KeyD" geometry={nodes.KeyD.geometry} material={materials.PaletteMaterial001} position={[-0.044, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyC} name="KeyC" geometry={nodes.KeyC.geometry} material={materials.PaletteMaterial001} position={[-0.039, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyE} name="KeyE" geometry={nodes.KeyE.geometry} material={materials.PaletteMaterial001} position={[-0.049, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Digit3} name="Digit3" geometry={nodes.Digit3.geometry} material={materials.PaletteMaterial001} position={[-0.054, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyF} name="KeyF" geometry={nodes.KeyF.geometry} material={materials.PaletteMaterial001} position={[-0.029, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyV} name="KeyV" geometry={nodes.KeyV.geometry} material={materials.PaletteMaterial001} position={[-0.024, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyR} name="KeyR" geometry={nodes.KeyR.geometry} material={materials.PaletteMaterial001} position={[-0.034, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Digit4} name="Digit4" geometry={nodes.Digit4.geometry} material={materials.PaletteMaterial001} position={[-0.04, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyG} name="KeyG" geometry={nodes.KeyG.geometry} material={materials.PaletteMaterial001} position={[-0.015, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyB} name="KeyB" geometry={nodes.KeyB.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyT} name="KeyT" geometry={nodes.KeyT.geometry} material={materials.PaletteMaterial001} position={[-0.02, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Digit7} name="Digit7" geometry={nodes.Digit7.geometry} material={materials.PaletteMaterial001} position={[0.003, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyK} name="KeyK" geometry={nodes.KeyK.geometry} material={materials.PaletteMaterial001} position={[0.028, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Comma} name="Comma" geometry={nodes.Comma.geometry} material={materials.PaletteMaterial001} position={[0.033, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyI} name="KeyI" geometry={nodes.KeyI.geometry} material={materials.PaletteMaterial001} position={[0.023, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Digit8} name="Digit8" geometry={nodes.Digit8.geometry} material={materials.PaletteMaterial001} position={[0.017, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyL} name="KeyL" geometry={nodes.KeyL.geometry} material={materials.PaletteMaterial001} position={[0.042, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Period} name="Period" geometry={nodes.Period.geometry} material={materials.PaletteMaterial001} position={[0.047, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyO} name="KeyO" geometry={nodes.KeyO.geometry} material={materials.PaletteMaterial001} position={[0.037, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Digit9} name="Digit9" geometry={nodes.Digit9.geometry} material={materials.PaletteMaterial001} position={[0.031, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Semicolon} name="Semicolon" geometry={nodes.Semicolon.geometry} material={materials.PaletteMaterial001} position={[0.056, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Slash} name="Slash" geometry={nodes.Slash.geometry} material={materials.PaletteMaterial001} position={[0.061, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.KeyP} name="KeyP" geometry={nodes.KeyP.geometry} material={materials.PaletteMaterial001} position={[0.051, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Digit0} name="Digit0" geometry={nodes.Digit0.geometry} material={materials.PaletteMaterial001} position={[0.046, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Quote} name="Quote" geometry={nodes.Quote.geometry} material={materials.PaletteMaterial001} position={[0.071, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.BracketLeft} name="BracketLeft" geometry={nodes.BracketLeft.geometry} material={materials.PaletteMaterial001} position={[0.066, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Minus} name="Minus" geometry={nodes.Minus.geometry} material={materials.PaletteMaterial001} position={[0.06, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.Equal} name="Equal" geometry={nodes.Equal.geometry} material={materials.PaletteMaterial001} position={[0.074, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh ref={meshRefs.current.BracketRight} name="BracketRight" geometry={nodes.BracketRight.geometry} material={materials.PaletteMaterial001} position={[0.08, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <group>
          <instancedMesh args={[nodes.Cube070.geometry, materials.PaletteMaterial001, 16]} name="Cube070" instanceMatrix={nodes.Cube070.instanceMatrix} />
          <instancedMesh args={[nodes.Cube070_1.geometry, materials.PaletteMaterial001, 16]} name="Cube070_1" instanceMatrix={nodes.Cube070_1.instanceMatrix} />
        </group>
        <instancedMesh args={[nodes.Cube013.geometry, materials.PaletteMaterial001, 10]} name="Cube013" instanceMatrix={nodes.Cube013.instanceMatrix} />
        <instancedMesh args={[nodes.Cube032.geometry, materials.PaletteMaterial001, 8]} name="Cube032" instanceMatrix={nodes.Cube032.instanceMatrix} />
      </group>
    </group>
  )
}

useGLTF.preload('/keyboard-transformed.glb')
