/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\assets\keyboard\keyboard.gltf --transform --types -o .\src\components\KeyboardModel.tsx -k -K -j 
Files: .\public\assets\keyboard\keyboard.gltf [133.14KB] > keyboard-transformed.glb [98.82KB] (26%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useEffect } from 'react'
import { KeyboardController, ModelProps } from './KeyboardConrtoller'

type GLTFResult = GLTF & {
  nodes: {
    plate: THREE.Mesh
    Cube076_1: THREE.Mesh
    Cube076_2: THREE.Mesh
    Cube077_1: THREE.Mesh
    Cube077_2: THREE.Mesh
    Cube078_1: THREE.Mesh
    Cube078_2: THREE.Mesh
    Cube079_1: THREE.Mesh
    Cube079_2: THREE.Mesh
    ESC: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube004: THREE.Mesh
    Cube003: THREE.Mesh
    Cube015: THREE.Mesh
    Cube081: THREE.Mesh
    Cube092: THREE.Mesh
    Cube005: THREE.Mesh
    Cube082: THREE.Mesh
    Cube006: THREE.Mesh
    Cube083: THREE.Mesh
    Cube007: THREE.Mesh
    Cube084: THREE.Mesh
    Cube008: THREE.Mesh
    Cube085: THREE.Mesh
    Cube014: THREE.Mesh
    Cube091: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube093: THREE.Mesh
    Cube018: THREE.Mesh
    Cube094: THREE.Mesh
    Cube039: THREE.Mesh
    Cube051: THREE.Mesh
    Cube061: THREE.Mesh
    Cube070: THREE.Mesh
    Cube040: THREE.Mesh
    Cube052: THREE.Mesh
    Cube062: THREE.Mesh
    Cube071: THREE.Mesh
    Cube041: THREE.Mesh
    Cube053: THREE.Mesh
    Cube063: THREE.Mesh
    Cube072: THREE.Mesh
    Cube042: THREE.Mesh
    Cube054: THREE.Mesh
    Cube064: THREE.Mesh
    Cube073: THREE.Mesh
    Cube045: THREE.Mesh
    Cube057: THREE.Mesh
    Cube067: THREE.Mesh
    Cube076: THREE.Mesh
    Cube046: THREE.Mesh
    Cube058: THREE.Mesh
    Cube068: THREE.Mesh
    Cube077: THREE.Mesh
    Cube047: THREE.Mesh
    Cube059: THREE.Mesh
    Cube069: THREE.Mesh
    Cube078: THREE.Mesh
    Cube048: THREE.Mesh
    Cube060: THREE.Mesh
    Cube079: THREE.Mesh
    Cube049: THREE.Mesh
    Cube050: THREE.Mesh
    Cube080: THREE.Mesh
    Cube070_1: THREE.Mesh
    Cube070_2: THREE.Mesh
    Cube013: THREE.Mesh
    Cube032: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/public/assets/keyboard-transformed.glb') as GLTFResult

  const meshRefs = props.controller.keyboardRef

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="plate" geometry={nodes.plate.geometry} material={materials.PaletteMaterial001} position={[0.001, -0.013, -0.001]} />
        <group name="Cube026" position={[-0.097, -0.005, -0.03]} rotation={[-3.089, 0, 0]} scale={0.5}>
          <mesh name="Cube076_1" geometry={nodes.Cube076_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube076_2" geometry={nodes.Cube076_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Cube019" position={[-0.077, -0.006, -0.016]} rotation={[-3.089, 0, 0]} scale={0.5}>
          <mesh name="Cube077_1" geometry={nodes.Cube077_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube077_2" geometry={nodes.Cube077_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Cube027" position={[-0.072, -0.007, -0.001]} rotation={[-3.089, 0, 0]} scale={0.5}>
          <mesh name="Cube078_1" geometry={nodes.Cube078_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube078_2" geometry={nodes.Cube078_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Cube028" position={[-0.067, -0.007, 0.014]} rotation={[-3.089, 0, 0]} scale={0.5}>
          <mesh name="Cube079_1" geometry={nodes.Cube079_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube079_2" geometry={nodes.Cube079_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh ref={meshRefs.current.ESC} name="ESC" geometry={nodes.ESC.geometry} material={materials.PaletteMaterial001} position={nodes.ESC.position} rotation={[0.052, -0.017, 0.001]} scale={0.5} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial001} position={[-0.072, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.PaletteMaterial001} position={[-0.067, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.PaletteMaterial001} position={[-0.077, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.PaletteMaterial001} position={[-0.095, 0.002, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.PaletteMaterial001} position={[0.097, 0.002, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube081" geometry={nodes.Cube081.geometry} material={materials.PaletteMaterial001} position={[-0.095, 0.002, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube092" geometry={nodes.Cube092.geometry} material={materials.PaletteMaterial001} position={[0.097, 0.002, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.PaletteMaterial001} position={[-0.092, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube082" geometry={nodes.Cube082.geometry} material={materials.PaletteMaterial001} position={[-0.092, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.PaletteMaterial001} position={[-0.09, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube083" geometry={nodes.Cube083.geometry} material={materials.PaletteMaterial001} position={[-0.09, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube084" geometry={nodes.Cube084.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.PaletteMaterial001} position={[-0.096, -0.001, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube085" geometry={nodes.Cube085.geometry} material={materials.PaletteMaterial001} position={[-0.096, -0.001, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.PaletteMaterial001} position={[0.096, -0.001, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube091" geometry={nodes.Cube091.geometry} material={materials.PaletteMaterial001} position={[0.096, -0.001, 0.03]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.PaletteMaterial001} position={[0.094, 0.003, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.PaletteMaterial001} position={[0.093, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube093" geometry={nodes.Cube093.geometry} material={materials.PaletteMaterial001} position={[0.093, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.PaletteMaterial001} position={[0.088, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube094" geometry={nodes.Cube094.geometry} material={materials.PaletteMaterial001} position={[0.088, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials.PaletteMaterial001} position={[-0.083, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube051" geometry={nodes.Cube051.geometry} material={materials.PaletteMaterial001} position={[-0.058, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube061" geometry={nodes.Cube061.geometry} material={materials.PaletteMaterial001} position={[-0.053, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube070" geometry={nodes.Cube070.geometry} material={materials.PaletteMaterial001} position={[-0.063, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials.PaletteMaterial001} position={[-0.069, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials.PaletteMaterial001} position={[-0.044, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube062" geometry={nodes.Cube062.geometry} material={materials.PaletteMaterial001} position={[-0.039, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube071" geometry={nodes.Cube071.geometry} material={materials.PaletteMaterial001} position={[-0.049, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials.PaletteMaterial001} position={[-0.054, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials.PaletteMaterial001} position={[-0.029, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube063" geometry={nodes.Cube063.geometry} material={materials.PaletteMaterial001} position={[-0.024, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube072" geometry={nodes.Cube072.geometry} material={materials.PaletteMaterial001} position={[-0.034, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials.PaletteMaterial001} position={[-0.04, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials.PaletteMaterial001} position={[-0.015, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube073" geometry={nodes.Cube073.geometry} material={materials.PaletteMaterial001} position={[-0.02, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube045" geometry={nodes.Cube045.geometry} material={materials.PaletteMaterial001} position={[0.003, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials.PaletteMaterial001} position={[0.028, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube067" geometry={nodes.Cube067.geometry} material={materials.PaletteMaterial001} position={[0.033, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube076" geometry={nodes.Cube076.geometry} material={materials.PaletteMaterial001} position={[0.023, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials.PaletteMaterial001} position={[0.017, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={materials.PaletteMaterial001} position={[0.042, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube068" geometry={nodes.Cube068.geometry} material={materials.PaletteMaterial001} position={[0.047, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube077" geometry={nodes.Cube077.geometry} material={materials.PaletteMaterial001} position={[0.037, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube047" geometry={nodes.Cube047.geometry} material={materials.PaletteMaterial001} position={[0.031, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials.PaletteMaterial001} position={[0.056, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube069" geometry={nodes.Cube069.geometry} material={materials.PaletteMaterial001} position={[0.061, 0, 0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube078" geometry={nodes.Cube078.geometry} material={materials.PaletteMaterial001} position={[0.051, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube048" geometry={nodes.Cube048.geometry} material={materials.PaletteMaterial001} position={[0.046, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube060" geometry={nodes.Cube060.geometry} material={materials.PaletteMaterial001} position={[0.071, 0.001, 0]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube079" geometry={nodes.Cube079.geometry} material={materials.PaletteMaterial001} position={[0.066, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube049" geometry={nodes.Cube049.geometry} material={materials.PaletteMaterial001} position={[0.06, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube050" geometry={nodes.Cube050.geometry} material={materials.PaletteMaterial001} position={[0.074, 0.002, -0.029]} rotation={[0.052, 0, 0]} scale={0.5} />
        <mesh name="Cube080" geometry={nodes.Cube080.geometry} material={materials.PaletteMaterial001} position={[0.08, 0.001, -0.015]} rotation={[0.052, 0, 0]} scale={0.5} />
        <group>
          <instancedMesh args={[nodes.Cube070_1.geometry, materials.PaletteMaterial001, 16]} name="Cube070_1" instanceMatrix={nodes.Cube070_1.instanceMatrix} />
          <instancedMesh args={[nodes.Cube070_2.geometry, materials.PaletteMaterial001, 16]} name="Cube070_2" instanceMatrix={nodes.Cube070_2.instanceMatrix} />
        </group>
        <instancedMesh args={[nodes.Cube013.geometry, materials.PaletteMaterial001, 10]} name="Cube013" instanceMatrix={nodes.Cube013.instanceMatrix} />
        <instancedMesh args={[nodes.Cube032.geometry, materials.PaletteMaterial001, 8]} name="Cube032" instanceMatrix={nodes.Cube032.instanceMatrix} />
      </group>
    </group>
  )
}

useGLTF.preload('/keyboard-transformed.glb')
